<?php
    if (! isset($title)) {
        $title = 'Untitled';
    }
    
    if (! isset($errors)) {
        $errors = array();
    }
    
    if (! isset($notes)) {
        $notes =array();
    }
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"  dir="ltr" lang="en-US">
	<head>
		<link rel="stylesheet" type="text/css" href="/wp-content/plugins/w3-total-cache/inc/css/popup.css"></link>
		<script type="text/javascript" src="/wp-includes/js/jquery/jquery.js"></script>
		<script type="text/javascript" src="/wp-content/plugins/w3-total-cache/inc/js/popup.js"></script>
		<title><?php echo htmlspecialchars($title); ?> - W3 Total Cache</title>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	</head>
	<body>
		<div id="content">
			<h1><?php echo htmlspecialchars($title); ?></h1>
					
        	<?php if (count($errors)): ?>
            <div id="message" class="error">
            	<?php foreach ($errors as $error): ?>
            	<p><?php echo $error; ?></p>
            	<?php endforeach; ?>
            </div>
        	<?php endif; ?>
        	
        	<?php if (count($notes)): ?>
            <div id="message" class="updated fade">
            	<?php foreach ($notes as $note): ?>
            	<p><?php echo $note; ?></p>
            	<?php endforeach; ?>
            </div>
        	<?php endif; ?>
     	
