<?php

return array(
    'dbcache.enabled' => true, 
    'dbcache.debug' => false, 
    'dbcache.engine' => 'file', 
    'dbcache.file.gc' => 3600, 
    'dbcache.memcached.engine' => 'auto', 
    'dbcache.memcached.servers' => array(
        'localhost:11211'
    ), 
    'dbcache.reject.logged' => true, 
    'dbcache.reject.uri' => array(), 
    'dbcache.reject.cookie' => array(), 
    'dbcache.reject.sql' => array(), 
    'dbcache.lifetime' => 180, 
    'pgcache.enabled' => true, 
    'pgcache.debug' => false, 
    'pgcache.engine' => 'file', 
    'pgcache.file.gc' => 3600, 
    'pgcache.memcached.engine' => 'auto', 
    'pgcache.memcached.servers' => array(
        'localhost:11211'
    ), 
    'pgcache.lifetime' => 3600, 
    'pgcache.compress' => true, 
    'pgcache.cache.query' => true, 
    'pgcache.cache.home' => true, 
    'pgcache.cache.feed' => true, 
    'pgcache.cache.404' => false, 
    'pgcache.cache.flush' => false, 
    'pgcache.cache.headers' => array(
        'Last-Modified', 
        'Content-Type', 
        'X-Pingback'
    ), 
    'pgcache.accept.files' => array(
        'wp-comments-popup.php', 
        'wp-links-opml.php', 
        'wp-locations.php'
    ), 
    'pgcache.reject.logged' => true, 
    'pgcache.reject.uri' => array(
        'wp-.*\.php', 
        'index\.php'
    ), 
    'pgcache.reject.ua' => array(
        'bot', 
        'ia_archive', 
        'slurp', 
        'crawl', 
        'spider'
    ), 
    'pgcache.reject.cookie' => array(), 
    'pgcache.mobile.redirect' => '', 
    'pgcache.mobile.agents' => array(
        'Android', 
        '2.0 MMP', 
        '240x320', 
        'AvantGo', 
        'BlackBerry', 
        'Blazer', 
        'Cellphone', 
        'Danger', 
        'DoCoMo', 
        'Elaine/3.0', 
        'EudoraWeb', 
        'hiptop', 
        'IEMobile', 
        'iPhone', 
        'iPod', 
        'KYOCERA/WX310K', 
        'LG/U990', 
        'MIDP-2.0', 
        'MMEF20', 
        'MOT-V', 
        'NetFront', 
        'Newt', 
        'Nintendo Wii', 
        'Nitro', 
        'Nokia', 
        'Opera Mini', 
        'Palm', 
        'Playstation Portable', 
        'portalmmm', 
        'Proxinet', 
        'ProxiNet', 
        'SHARP-TQ-GX10', 
        'Small', 
        'SonyEricsson', 
        'Symbian OS', 
        'SymbianOS', 
        'TS21i-10', 
        'UP.Browser', 
        'UP.Link', 
        'Windows CE', 
        'WinWAP', 
        'Ericsson', 
        'htc', 
        'Huawei', 
        'MobilePhone', 
        'Motorola', 
        'nokia', 
        'Novarra', 
        'O2', 
        'Samsung', 
        'Sanyo', 
        'Smartphone', 
        'Symbian', 
        'Toshiba', 
        'Treo', 
        'vodafone', 
        'Xda', 
        'Alcatel', 
        'Amoi', 
        'ASUS', 
        'Audiovox', 
        'AU-MIC', 
        'BenQ', 
        'Bird', 
        'CDM', 
        'dopod', 
        'Fly', 
        'Haier', 
        'HP.iPAQ', 
        'i-mobile', 
        'KDDI', 
        'KONKA', 
        'KWC', 
        'Lenovo', 
        'LG', 
        'NEWGEN', 
        'Panasonic', 
        'PANTECH', 
        'PG', 
        'Philips', 
        'PPC', 
        'PT', 
        'Qtek', 
        'Sagem', 
        'SCH', 
        'SEC', 
        'Sendo', 
        'SGH', 
        'Sharp', 
        'SIE', 
        'SoftBank', 
        'SPH', 
        'UTS', 
        'Vertu', 
        'Opera.Mobi', 
        'Windows.CE', 
        'ZTE'
    ), 
    
    'minify.enabled' => true, 
    'minify.debug' => false, 
    'minify.engine' => 'file', 
    'minify.file.locking' => true, 
    'minify.file.gc' => 86400, 
    'minify.memcached.engine' => 'auto', 
    'minify.memcached.servers' => array(
        'localhost:11211'
    ), 
    'minify.rewrite' => true, 
    'minify.fixtime' => 0, 
    'minify.compress' => true, 
    'minify.compress.ie6' => true, 
    'minify.options' => array(
        'bubbleCssImports' => false, 
        'minApp' => array(
            'groupsOnly' => false, 
            'maxFiles' => 20
        )
    ), 
    'minify.symlinks' => array(), 
    'minify.maxage' => 86400, 
    'minify.lifetime' => 86400, 
    'minify.upload' => true, 
    'minify.html.enable' => true, 
    'minify.html.reject.admin' => true, 
    'minify.html.inline.css' => false, 
    'minify.html.inline.js' => false, 
    'minify.html.strip.crlf' => false, 
    'minify.css.enable' => true, 
    'minify.css.strip.comments' => false, 
    'minify.css.strip.crlf' => false, 
    'minify.css.groups' => array(), 
    'minify.js.enable' => true, 
    'minify.js.combine.header' => false, 
    'minify.js.combine.footer' => false, 
    'minify.js.strip.comments' => false, 
    'minify.js.strip.crlf' => false, 
    'minify.js.groups' => array(), 
    'minify.reject.ua' => array(), 
    'minify.reject.uri' => array(), 
    'cdn.enabled' => false, 
    'cdn.debug' => false, 
    'cdn.engine' => 'ftp', 
    'cdn.includes.enable' => true, 
    'cdn.includes.files' => '*.css;*.js;*.gif;*.png;*.jpg', 
    'cdn.theme.enable' => true, 
    'cdn.theme.files' => '*.css;*.js;*.gif;*.png;*.jpg;*.ico', 
    'cdn.minify.enable' => true, 
    'cdn.custom.enable' => true, 
    'cdn.custom.files' => array(
        'favicon.ico'
    ), 
    'cdn.import.external' => false, 
    'cdn.import.files' => '*.jpg;*.png;*.gif;*.avi;*.wmv;*.mpg;*.wav;*.mp3;*.txt;*.rtf;*.doc;*.xls;*.rar;*.zip;*.tar;*.gz;*.exe', 
    'cdn.limit.queue' => 25, 
    'cdn.mirror.domain' => '', 
    'cdn.ftp.host' => '', 
    'cdn.ftp.user' => '', 
    'cdn.ftp.pass' => '', 
    'cdn.ftp.path' => '', 
    'cdn.ftp.pasv' => false, 
    'cdn.ftp.domain' => '', 
    'cdn.s3.key' => '', 
    'cdn.s3.secret' => '', 
    'cdn.s3.bucket' => '', 
    'cdn.cf.key' => '', 
    'cdn.cf.secret' => '', 
    'cdn.cf.bucket' => '', 
    'cdn.cf.id' => '', 
    'cdn.cf.cname' => '', 
    'cdn.reject.ua' => array(), 
    'cdn.reject.uri' => array(), 
    'common.support' => '', 
    'common.widget.latest' => true, 
    'notes.defaults' => true, 
    'notes.wp_content_perms' => true, 
    'notes.cdn_first_time' => true, 
    'notes.no_memcached_nor_apc' => true, 
    'notes.php_is_old' => true, 
    'notes.theme_changed' => false, 
    'notes.wp_upgraded' => false, 
    'notes.plugins_updated' => false, 
    'notes.cdn_upload' => false, 
    'notes.need_empty_pgcache' => false, 
    'notes.need_empty_minify' => false, 
    'notes.pgcache_rules_core' => true, 
    'notes.pgcache_rules_cache' => true, 
    'notes.minify_rules' => true, 
    'notes.support_us' => true
);
