<tr>
	<th style="width:300px;"><label for="cdn_cfl_email">E-mail:</label></th>
	<td>
		<input id="cdn_cfl_email" class="w3tc-ignore-change" type="text" name="cdn.cfl.email" value="<?php echo htmlspecialchars($this->_config->get_string('cdn.cfl.email')); ?>" size="60" />
	</td>
</tr>
<tr>
	<th><label for="cdn_cfl_key">API key:</label></th>
	<td>
		<input id="cdn_cfl_key" class="w3tc-ignore-change" type="password" name="cdn.cfl.key" value="<?php echo htmlspecialchars($this->_config->get_string('cdn.cfl.key')); ?>" size="60" />
        <input class="button-cdn-cfl-new-account button" type="button" value="Create account" />
	</td>
</tr>
<tr>
	<th>Zone:</th>
	<td>
		<?php echo w3_get_host(); ?>
        <input id="cdn_cfl_purge_cache" class="button" type="button" value="Purge cache" />
	</td>
</tr>
<tr>
    <th>Development mode:</th>
    <td>
        <input id="cdn_cfl_set_devmode_on" class="button" type="button" value="Set On" /> /
        <input id="cdn_cfl_set_devmode_off" class="button" type="button" value="Set Off" />
    </td>
</tr>
<tr>
    <th>Security level:</th>
    <td>
        <select id="cdn_cfl_seclevel">
            <option value="">&nbsp;</option>
            <option value="high">High</option>
            <option value="med">Medium</option>
            <option value="low">Low</option>
        </select>
        <input id="cdn_cfl_set_seclevel" class="button" type="button" value="Set" />
    </td>
</tr>
