<script type="text/javascript" src="<?php echo WP_PLUGIN_URL; ?>/w3-total-cache/inc/js/options.js"></script>
<script type="text/javascript" src="<?php echo WP_PLUGIN_URL; ?>/w3-total-cache/inc/js/lightbox.js"></script>
<?php if ($this->_support_reminder): ?>
<script type="text/javascript">
/*<![CDATA[*/
jQuery(function($) {
    w3tc_lightbox_support_us();
});
/*]]>*/
</script>
<?php endif; ?>

<div class="wrap" id="w3tc">
    <?php screen_icon('w3tc-logo'); ?>

	<h2>W3 Total Cache</h2>

	<?php foreach ($this->_errors as $error): ?>
    <div class="error">
    	<p><?php echo $error; ?></p>
    </div>
	<?php endforeach; ?>

	<?php foreach ($this->_notes as $note): ?>
	<div class="updated fade">
		<p><?php echo $note; ?></p>
    </div>
    <?php endforeach; ?>

	<p id="w3tc-options-menu">
    	<a href="?page=<?php echo W3TC_FILE; ?>&amp;tab=general"<?php if ($this->_tab == 'general'): ?> class="w3tc-options-menu-selected"<?php endif; ?>>General</a> |
    	<a href="?page=<?php echo W3TC_FILE; ?>&amp;tab=pgcache"<?php if ($this->_tab == 'pgcache'): ?> class="w3tc-options-menu-selected"<?php endif; ?>>Page Cache</a> |
    	<?php if (W3TC_PHP5): ?>
    	<a href="?page=<?php echo W3TC_FILE; ?>&amp;tab=minify"<?php if ($this->_tab == 'minify'): ?> class="w3tc-options-menu-selected"<?php endif; ?>>Minify</a> |
    	<?php else: ?>
    	Minify |
    	<?php endif; ?>
    	<a href="?page=<?php echo W3TC_FILE; ?>&amp;tab=dbcache"<?php if ($this->_tab == 'dbcache'): ?> class="w3tc-options-menu-selected"<?php endif; ?>>Database Cache</a> |
        <a href="?page=<?php echo W3TC_FILE; ?>&amp;tab=objectcache"<?php if ($this->_tab == 'objectcache'): ?> class="w3tc-options-menu-selected"<?php endif; ?>>Object Cache</a> |
        <a href="?page=<?php echo W3TC_FILE; ?>&amp;tab=browsercache"<?php if ($this->_tab == 'browsercache'): ?> class="w3tc-options-menu-selected"<?php endif; ?>>Browser Cache</a> |
        <a href="?page=<?php echo W3TC_FILE; ?>&amp;tab=mobile"<?php if ($this->_tab == 'mobile'): ?> class="w3tc-options-menu-selected"<?php endif; ?>>User Agent Groups</a> |
    	<a href="?page=<?php echo W3TC_FILE; ?>&amp;tab=cdn"<?php if ($this->_tab == 'cdn'): ?> class="w3tc-options-menu-selected"<?php endif; ?>>Content Delivery Network</a> |
    	<a href="?page=<?php echo W3TC_FILE; ?>&amp;tab=faq"<?php if ($this->_tab == 'faq'): ?> class="w3tc-options-menu-selected"<?php endif; ?>><acronym title="Frequently Asked Questions">FAQ</acronym></a> |
    	<a href="?page=<?php echo W3TC_FILE; ?>&amp;tab=support_select"<?php if ($this->_tab == 'support_select'): ?> class="w3tc-options-menu-selected"<?php endif; ?> style="color: red;">Support</a> |
    	<a href="?page=<?php echo W3TC_FILE; ?>&amp;tab=install"<?php if ($this->_tab == 'install'): ?> class="w3tc-options-menu-selected"<?php endif; ?>>Install</a> |
    	<a href="?page=<?php echo W3TC_FILE; ?>&amp;tab=about"<?php if ($this->_tab == 'about'): ?> class="w3tc-options-menu-selected"<?php endif; ?>>About</a>
    </p>
