<table cellspacing="5">
	<tr>
		<td>Total media library attachments:</th>
		<td id="cdn_export_table_total"><?php echo $total; ?></td>
	</tr>
	<tr>
		<td>Processed:</td>
		<td id="cdn_export_table_processed">0</td>
	</tr>
	<tr>
		<td>Status:</td>
		<td id="cdn_export_table_status">-</td>
	</tr>
</table>

<p>
	<input id="cdn_export_table_start" class="button" type="button" value="Start"<?php if (! $total): ?> disabled="disabled"<?php endif; ?> />
</p>

<div id="cdn_export_table_progress" class="progress">
	<div class="progress-value">0%</div>
	<div class="progress-bar"></div>
	<div class="clear"></div>
</div>

<div id="cdn_export_table_log" class="log"></div>