<h3>New CloudFlare account</h3>

<form action="" method="post">
    <table class="form-table">
        <tr>
            <th><label for="cfl_new_account_email">E-Mail:</label></th>
            <td>
                <input id="cfl_new_account_email" type="text" value="" size="50" /> (required)
            </td>
        </tr>
        <tr>
            <th><label for="cfl_new_account_password">Password:</label></th>
            <td>
                <input id="cfl_new_account_password" type="password" value="" size="50" /> (required)
            </td>
        </tr>
        <tr>
            <th><label for="cfl_new_account_password2">Repeat password:</label></th>
            <td>
                <input id="cfl_new_account_password2" type="password" value="" size="50" /> (required)
            </td>
        </tr>
        <tr>
            <th><label for="cfl_new_account_username">Username:</label></th>
            <td>
                <input id="cfl_new_account_username" type="text" value="" size="50" /> (optional)
            </td>
        </tr>
        <tr>
            <th><label for="cfl_new_account_zone_name">Zone name:</label></th>
            <td>
                <input id="cfl_new_account_zone_name" type="text" value="" size="50" /> (required)
            </td>
        </tr>
        <tr>
            <th><label for="cfl_new_account_resolve_to">Resolve to:</label></th>
            <td>
                <input id="cfl_new_account_resolve_to" type="text" value="" size="50" /> (required)
            </td>
        </tr>
        <tr>
            <th><label for="cfl_new_account_subdomains">Subdomains:</label></th>
            <td>
                <input id="cfl_new_account_subdomains" type="text" value="" size="50" /> (required)
            </td>
        </tr>
    </table>

    <p>
        <input class="button-primary" type="submit" value="Create account" />
    </p>
</form>
