<div class="wrap">
    <?php screen_icon('w3tc-logo'); ?>
    
	<h2>W3 Total Cache</h2>
	
	<?php if (count($errors)): ?>
    <div id="message" class="error">
    	<?php foreach ($errors as $error): ?>
    	<p><?php echo $error; ?></p>
    	<?php endforeach; ?>
    </div>
	<?php endif; ?>
	
	<?php if (count($notes)): ?>
    <div id="message" class="updated fade">
    	<?php foreach ($notes as $note): ?>
    	<p><?php echo $note; ?></p>
    	<?php endforeach; ?>
    </div>
	<?php endif; ?>

	<p id="w3tc-options-menu">
    	<a href="?page=<?php echo W3_PLUGIN_FILE; ?>&amp;tab=general"<?php if ($tab == 'general'): ?> class="w3tc-options-menu-selected"<?php endif; ?>>General Settings</a> |
    	<a href="?page=<?php echo W3_PLUGIN_FILE; ?>&amp;tab=pgcache"<?php if ($tab == 'pgcache'): ?> class="w3tc-options-menu-selected"<?php endif; ?>>Page Cache Settings</a> |
    	<a href="?page=<?php echo W3_PLUGIN_FILE; ?>&amp;tab=minify"<?php if ($tab == 'minify'): ?> class="w3tc-options-menu-selected"<?php endif; ?>>Minify Settings</a> |
    	<a href="?page=<?php echo W3_PLUGIN_FILE; ?>&amp;tab=dbcache"<?php if ($tab == 'dbcache'): ?> class="w3tc-options-menu-selected"<?php endif; ?>>Database Cache Settings</a> |
    	<a href="?page=<?php echo W3_PLUGIN_FILE; ?>&amp;tab=cdn"<?php if ($tab == 'cdn'): ?> class="w3tc-options-menu-selected"<?php endif; ?>><acronym title="Content Delivery Network">CDN</acronym> Settings</a> |
    	<a href="?page=<?php echo W3_PLUGIN_FILE; ?>&amp;tab=faq"<?php if ($tab == 'faq'): ?> class="w3tc-options-menu-selected"<?php endif; ?>><acronym title="Frequently Asked Questions">FAQ</acronym></a> |
    	<a href="?page=<?php echo W3_PLUGIN_FILE; ?>&amp;tab=install"<?php if ($tab == 'install'): ?> class="w3tc-options-menu-selected"<?php endif; ?>>Installation</a> |
    	<a href="?page=<?php echo W3_PLUGIN_FILE; ?>&amp;tab=about"<?php if ($tab == 'about'): ?> class="w3tc-options-menu-selected"<?php endif; ?>>About</a>
    </p>
