<h3 id="about">About</h3> 
<p>User experience is an important aspect of every web site and all web sites can benefit from effective caching and file size reduction. We have applied web site optimization methods typically used with high traffic sites and simplified their implementation. Coupling these methods either <a href="http://www.danga.com/memcached/" target="_blank">memcached</a> and/or <a href="http://pecl.php.net/package/APC" target="_blank">APC</a> and the <acronym title="Content Delivery Network">CDN</acronym> of your choosing to provide the following benefits:</p> 
<ul style="list-style-type:disc;list-style-position:inside;"> 
    <li>Bandwidth savings.</li> 
    <li>Improved server scale and reliability under heavy load.</li> 
    <li>Improved user experience resulting in: increased conversions, increased time on site, increased page views etc.</li> 
    <li>Reduction of <acronym title="Hypertext Transfer Protocol">HTTP</acronym> requests, reducing total document load time.</li> 
    <li>Optimized handling of headers for improved file caching.</li> 
    <li>Non-blocking load of multiple <acronym title="Cascading Style Sheets">CSS</acronym> and <acronym title="JavaScript">JS</acronym> files.</li> 
    <li>Detailed site-wide and per page statistics.</li> 
    <li>Transparent integration of content delivery networks for media library and theme files.</li> 
    <li>Minified <acronym title="Hypertext Mark-up Language">HTML</acronym>, <acronym title="Cascading Style Sheets">CSS</acronym> and <acronym title="JavaScript">JS</acronym>. All white space and comments in your files will be removed before they are served. Now you don't have to change your development style to optimize your site performance.</li> 
    <li>Gzipped or deflated <acronym title="Hypertext Mark-up Language">HTML</acronym>, <acronym title="Cascading Style Sheets">CSS</acronym> and <acronym title="JavaScript">JS</acronym> in memory, providing the fastest possible server response.</li> 
    <li>Page caching in memory, providing improved server performance, response time and server scale.</li> 
    <li>Database object memory caching, providing the fastest possible response, reduced server load and server scale.</li> 
</ul> 
<p>Your users have less data to download, you can now handle more requests with your existing equipment and you don't have to change how you do anything; just set it and forget it.</p>