<h3><acronym title="Content Delivery Network">CDN</acronym> Settings</h3>
 
<p><acronym title="Content Delivery Network">CDN</acronym> support is currently <span class="w3tc-<?php if ($config->get_boolean('cdn.enabled')): ?>enabled">enabled<?php else: ?>disabled">disabled<?php endif; ?></span>.</p>

<p>
	You can
	<input id="cdn_export_library" class="button" type="button" value="export media library to CDN" /> or
	<!--<input id="cdn_import_library" class="button" type="button" value="emport post files to media library &amp; CDN" /> or -->
	<input id="cdn_queue" class="button" type="button" value="view unsuccessfullt transfers" /> now.
</p>

<form action="options-general.php?page=<?php echo urldecode(W3_PLUGIN_FILE); ?>&amp;tab=<?php echo $tab; ?>" method="post">
	<!-- <p>
		<a href="#cdn_ftp" class="w3tc-tab" rel="#cdn_ftp"><acronym title="File Transfer Protocol">FTP</acronym> settings</a> |
		<a href="#cdn_cf" class="w3tc-tab" rel="#cdn_cf">Amazon CloudFront settings</a> |
		<a href="#cdn_s3" class="w3tc-tab" rel="#cdn_s3">Amazon S3 settings</a>
	</p> -->
	
	<div id="cdn_ftp" class="w3tc-tab-content">
        <table class="form-table">
        	<tr>
        		<th><label for="cdn_ftp_host"><acronym title="File Transfer Protocol">FTP</acronym> Hostname:</label></th>
        		<td>
        			<input id="cdn_ftp_host" type="text" name="cdn.ftp.host" value="<?php echo htmlspecialchars($config->get_string('cdn.ftp.host')); ?>" size="30" />
        		</td>
        	</tr>
        	<tr>
        		<th><label for="cdn_ftp_user"><acronym title="File Transfer Protocol">FTP</acronym> Username:</label></th>
        		<td>
        			<input id="cdn_ftp_user" type="text" name="cdn.ftp.user" value="<?php echo htmlspecialchars($config->get_string('cdn.ftp.user')); ?>" size="30" />
        		</td>
        	</tr>
        	<tr>
        		<th><label for="cdn_ftp_pass"><acronym title="File Transfer Protocol">FTP</acronym> Password:</label></th>
        		<td>
        			<input id="cdn_ftp_pass" type="text" name="cdn.ftp.pass" value="<?php echo htmlspecialchars($config->get_string('cdn.ftp.pass')); ?>" size="30" />
        		</td>
        	</tr>
        	<tr>
        		<th><label for="cdn_ftp_path"><acronym title="File Transfer Protocol">FTP</acronym> Path:</label></th>
        		<td>
        			<input id="cdn_ftp_path" type="text" name="cdn.ftp.path" value="<?php echo htmlspecialchars($config->get_string('cdn.ftp.path')); ?>" size="30" />
        		</td>
        	</tr>
        	<tr>
        		<th colspan="2">
        			<input type="hidden" name="cdn.ftp.pasv" value="0" />
        			<label><input type="checkbox" name="cdn.ftp.pasv" value="1"<?php checked($config->get_boolean('cdn.ftp.pasv')); ?> /> Use Passive <acronym title="File Transfer Protocol">FTP</acronym> Mode</label>
        		</th>
        	</tr>
        </table>
        <p>
        	<input id="test_ftp" class="button" type="button" value="Test FTP server" /> <span id="test_ftp_status" class="w3tc-cdn-status w3tc-process"></span>
        </p>
    </div>
    <div id="cdn_cf" class="w3tc-tab-content" style="display: none;">
    	to do...
        <p>
        	<input class="button" type="button" value="Test CloudFront server" />
        </p>
    </div>
    <div id="cdn_s3" class="w3tc-tab-content" style="display: none;">
    	to do...
        <p>
        	<input class="button" type="button" value="Test S3 server" />
        </p>
   	</div>
    
    <table class="form-table">
    	<tr>
    		<th style="width: 300px;"><label for="cdn_domain">Replace domain in <acronym title="Uniform Resource Locator">URL</acronym> with:</label></th>
    		<td>
    			<input id="cdn_domain" type="text" name="cdn.domain" value="<?php echo htmlspecialchars($config->get_string('cdn.domain')); ?>" size="40" />
    		</td>
    	</tr>
    	<tr>
    		<th><label for="cdn_limit_queue">Re-transfer cycle limit:</label></th>
    		<td>
    			<input id="cdn_limit_queue" type="text" name="cdn.limit.queue" value="<?php echo htmlspecialchars($config->get_integer('cdn.limit.queue')); ?>" size="10" /><br />
    			<span class="description">Number of files processed per cycle.</span>
    		</td>
    	</tr>
    	<tr>
    		<th>
    			<input type="hidden" name="cdn.process.includes" value="0" />
    			<label><input type="checkbox" name="cdn.process.includes" value="1"<?php checked($config->get_boolean('cdn.process.includes')); ?> /> Host wp-includes/ files</label>
    		</th>
    		<td>
    			<input class="button cdn_export" type="button" name="includes" value="Upload includes files" />
    		</td>
    	</tr>
    	<tr>
    		<th>
    			<input type="hidden" name="cdn.process.theme" value="0" />
    			<label><input type="checkbox" name="cdn.process.theme" value="1"<?php checked($config->get_boolean('cdn.process.theme')); ?> /> Host current theme files</label>
    		</th>
    		<td>
				<input class="button cdn_export" type="button" name="theme" value="Upload theme files" />
    		</td>
    	</tr>
    	<tr>
    		<th>
    			<input type="hidden" name="cdn.process.minify" value="0" />
    			<label><input type="checkbox" name="cdn.process.minify" value="1"<?php checked($config->get_boolean('cdn.process.minify')); ?> /> Host minify files</label>
    		</th>
    		<td>
				<input class="button cdn_export" type="button" name="minify" value="Upload minify files" />
    		</td>
    	</tr>
    	<tr>
    		<th>
    			<input type="hidden" name="cdn.process.custom" value="0" />
    			<label><input type="checkbox" name="cdn.process.custom" value="1"<?php checked($config->get_boolean('cdn.process.custom')); ?> /> Host custom files</label>
    		</th>
    		<td>
				<input class="button cdn_export" type="button" name="custom" value="Upload custom files" />
    		</td>
    	</tr>
    	<tr>
    		<th><label for="cdn_files_includes">Search wp-includes/ directory for files:</label></th>
    		<td>
    			<input id="cdn_files_includes" type="text" name="cdn.files.includes" value="<?php echo htmlspecialchars($config->get_string('cdn.files.includes')); ?>" size="40" />
    		</td>
    	</tr>
    	<tr>
    		<th><label for="cdn_files_theme">Search current theme directory for files:</label></th>
    		<td>
    			<input id="cdn_files_theme" type="text" name="cdn.files.theme" value="<?php echo htmlspecialchars($config->get_string('cdn.files.theme')); ?>" size="40" />
    		</td>
    	</tr>
    	<tr>
    		<th valign="top"><label for="cdn_files_custom">Custom file list:</label></th>
    		<td>
    			<textarea id="cdn_files_custom" name="cdn.files.custom" cols="30" rows="5"><?php echo htmlspecialchars(implode("\r\n", $config->get_array('cdn.files.custom'))); ?></textarea>
    		</td>
    	</tr>
    </table>
    
    <p class="submit">
    	<input type="submit" name="Submit" class="button-primary" value="Save changes" />
    </p>
</form>
