<?php include W3TC_DIR . '/inc/options/common/header.phtml'; ?>

<h4>Table of Contents</h4>

<div id="toc">
    <ul>
    <?php $q = 1; foreach ($xpath->query('//faqs/section') as $section): ?>
    <li class="col">
        <h5><?php echo strtoupper($section->attributes->getNamedItem('name')->nodeValue); ?>:</h5>
        <ul>
    	    <?php foreach ($xpath->query('./entry/question', $section) as $entry): ?>
	        <li><a href="#q<?php echo $q; ?>"><?php echo $entry->nodeValue; ?></a></li>
            <?php $q++; endforeach; ?>
        </ul>
    </li>
    <?php endforeach; ?>
    </ul>
</div>
<div id="qa">
	<hr />
    <?php $q = 1; foreach ($xpath->query('//faqs/section/entry') as $entry): ?>
	<p id="q<?php echo $q; ?>"><strong><?php echo $xpath->query('question', $entry)->item(0)->nodeValue; ?></strong></p>
    <?php echo $xpath->query('answer', $entry)->item(0)->nodeValue; ?>
	<p align="right"><a href="#toc">back to top</a></p>
	<?php $q++; endforeach; ?>
</div>

<?php include W3TC_DIR . '/inc/options/common/footer.phtml'; ?>