<?php include W3TC_DIR . '/inc/options/common/header.phtml'; ?>

<h3>General Settings</h3>

<p>The plugin is currently <span class="w3tc-<?php if ($enabled): ?>enabled">enabled<?php else: ?>disabled">disabled<?php endif; ?></span>. If an option is disabled it means that either your current installation is not compatible or installation is required.</p> 

<p><label><input id="enabled" type="checkbox" name="enabled" value="1"<?php checked($enabled, true); ?> /> Deselect this option to disable all caching functionality.</label></p>

<form action="options-general.php">
    <p>You can 
    	<input type="hidden" name="page" value="<?php echo W3TC_FILE; ?>" />
    	<input type="hidden" name="tab" value="<?php echo $this->_tab; ?>" />
    	<input class="button" type="submit" name="flush_all" value="empty all caches" /> at once or 
    	<input class="button" type="submit" name="flush_memcached" value="empty only the memcached cache"<?php if (! $can_empty_memcache): ?> disabled="disabled"<?php endif; ?> /> or
    	<input class="button" type="submit" name="flush_apc" value="empty only the opcode cache"<?php if (! $can_empty_apc): ?> disabled="disabled"<?php endif; ?> /> or 
    	<input class="button" type="submit" name="flush_file" value="empty only the disk cache"<?php if (! $can_empty_file): ?> disabled="disabled"<?php endif; ?> />.
    </p>
</form>

<p>Enable page caching to decrease the response time of your blog.</p>

<form action="options-general.php?page=<?php echo urldecode(W3TC_FILE); ?>&amp;tab=<?php echo $this->_tab; ?>" method="post">
    <table class="form-table">
        <tr>
        	<th valign="top">Page Caching:</th>
        	<td>
        		<input type="hidden" name="pgcache.enabled" value="0" />
        		<label><input class="enabled" type="checkbox" name="pgcache.enabled" value="1"<?php checked($pgcache_enabled, true); ?> />&nbsp;<strong>Enable</strong></label><br />
    			<span class="description">Caching pages will reduce the response time of your site and increase the concurrency (scale) of your web server.</span>
    		</td>
    	</tr>
    	<tr>
    		<th valign="top">Page Caching Method:</th>
    		<td>
    			<select name="pgcache.engine">
        			<option value="file_pgcache"<?php selected($this->_config->get_string('pgcache.engine'), 'file_pgcache'); ?>>Disk (enhanced)</option>
        			<option value="file"<?php selected($this->_config->get_string('pgcache.engine'), 'file'); ?>>Disk (basic)</option>
        			<option value="memcached"<?php selected($this->_config->get_string('pgcache.engine'), 'memcached'); ?>>Memcached<?php echo $memcache_engine; ?></option>
    				<option value="apc"<?php selected($this->_config->get_string('pgcache.engine'), 'apc'); ?><?php if (! $check_apc): ?> disabled="disabled"<?php endif; ?>>Alternative PHP Cache (APC)</option>
    			</select>
    		</td>
        </tr>
    </table>
     
	<p>Enable minify to combine, remove white space / comments and compress (<acronym title="GNU zip">gzip</acronym> / deflate) your (theme's / plugin's / external) <acronym title="Cascading Style Sheet">CSS</acronym> and <acronym title="JavaScript">JS</acronym> files.</p>

    <table class="form-table">
        <tr>
        	<th valign="top">Minify:</th>
        	<td>
        		<input type="hidden" name="minify.enabled" value="0"<?php if (! W3TC_PHP5): ?> disabled="disabled"<?php endif; ?> />
        		<label><input class="enabled" type="checkbox" name="minify.enabled" value="1"<?php checked($minify_enabled, true); ?><?php if (! W3TC_PHP5): ?> disabled="disabled"<?php endif; ?> />&nbsp;<strong>Enable</strong></label><br />
        		<span class="description">Minification can decrease file size of <acronym title="Hypertext Markup Language">HTML</acronym>, <acronym title="Cascading Style Sheet">CSS</acronym>, <acronym title="JavaScript">JS</acronym> and feeds respectively by ~10% on average.</span>    	
        	</td>
        </tr>
        <tr>
        	<th valign="top">Minify Caching Method:</th>
        	<td>
        		<select name="minify.engine"<?php if (! W3TC_PHP5): ?> disabled="disabled"<?php endif; ?>>
            		<option value="file"<?php selected($this->_config->get_string('minify.engine'), 'file'); ?>>Disk</option>
            		<option value="memcached"<?php selected($this->_config->get_string('minify.engine'), 'memcached'); ?>>Memcached<?php echo $memcache_engine; ?></option>
    				<option value="apc"<?php selected($this->_config->get_string('minify.engine'), 'apc'); ?><?php if (! $check_apc): ?> disabled="disabled"<?php endif; ?>>Alternative PHP Cache (APC)</option>
        		</select>
        	</td>
        </tr>
    </table>
    
    <p>Enable database caching to remove database performance bottlenecks from your blog.</p>
    
     <table class="form-table">
     	<tr>
     		<th valign="top">Database Caching:</th>
     		<td>
     			<input type="hidden" name="dbcache.enabled" value="0" />
    			<label><input class="enabled" type="checkbox" name="dbcache.enabled" value="1"<?php checked($dbcache_enabled, true); ?> />&nbsp;<strong>Enable</strong></label><br />
				<span class="description">Caching database objects may decrease the response time of your blog by up to 100x.</span>
    		</td>
    	</tr>
    	<tr>
    		<th valign="top">Database Caching Method:</th>
    		<td>
    			<select name="dbcache.engine">
            		<option value="file"<?php selected($this->_config->get_string('dbcache.engine'), 'file'); ?>>Disk</option>
        			<option value="memcached"<?php selected($this->_config->get_string('dbcache.engine'), 'memcached'); ?>>Memcached<?php echo $memcache_engine; ?></option>
    				<option value="apc"<?php selected($this->_config->get_string('dbcache.engine'), 'apc'); ?><?php if (! $check_apc): ?> disabled="disabled"<?php endif; ?>>Alternative PHP Cache (APC)</option>
    			</select>
    		</td>
    	</tr>
    </table>
    
    <p>Host your wp-includes (WordPress' core files), media library, theme images / <acronym title="Cascading Style Sheet">CSS</acronym> / <acronym title="JavaScript">JS</acronym> with your <acronym title="Content Delivery Network">CDN</acronym> provider.</p>
    
    <table class="form-table">
        <tr>
			<th><acronym title="Content Delivery Network">CDN</acronym>:</th>
        	<td>
        		<input type="hidden" name="cdn.enabled" value="0" />
				<label><input class="enabled" type="checkbox" name="cdn.enabled" value="1"<?php checked($cdn_enabled, true); ?> />&nbsp;<strong>Enable</strong></label><br />
        	</td>
        </tr>
        <tr>
			<th><acronym title="Content Delivery Network">CDN</acronym> Type:</th>
        	<td>
        		<select name="cdn.engine">
					<option value="mirror"<?php selected($this->_config->get_string('cdn.engine'), 'mirror'); ?>>Origin Pull (Mirror)</option>
					<option value="ftp"<?php selected($this->_config->get_string('cdn.engine'), 'ftp'); ?>>Origin Push / Self-hosted (File Transfer Protocol Upload)</option>
					<option value="cf"<?php selected($this->_config->get_string('cdn.engine'), 'cf'); ?><?php if (! W3TC_PHP5 || ! $check_curl): ?> disabled="disabled"<?php endif; ?>>Amazon CloudFront</option>
					<option value="s3"<?php selected($this->_config->get_string('cdn.engine'), 's3'); ?><?php if (! W3TC_PHP5 || ! $check_curl): ?> disabled="disabled"<?php endif; ?>>Amazon Simple Storage Service (S3)</option>
        		</select><br />
        		<span class="description">Select the <acronym title="Content Delivery Network">CDN</acronym> type you wish to use.</span>
        	</td>
        </tr>
    </table>
    
    <p>Use debug mode to view detailed data about the enabled caching types. Performance in this mode will not be optimal nor private, use sparingly.</p>
    
    <table class="form-table">
     	<tr>
     		<th valign="top">Debug Mode:</th>
     		<td>
     			<input type="hidden" name="debug" value="0" />
    			<label><input type="checkbox" name="debug" value="1"<?php checked($debug, true); ?> />&nbsp;<strong>Enable</strong></label><br />
        		<span class="description">If selected, detailed caching information will be appear at the end of each page in a <acronym title="Hypertext Markup Language">HTML</acronym> comment. View a page's source code to review.</span>
    		</td>
    	</tr>
    </table>    

    <h3>Support Us</h3>
     
	<p>We're working to make WordPress better. Please support us, here's how:</p>
	
	<p>
    	<label>Link to us:
        	<select name="common.support">
        		<option value="">select one</option>
        		<?php foreach ($supports as $support_id => $support_name): ?>
        		<option value="<?php echo $support_id; ?>"<?php selected($support, $support_id); ?>><?php echo htmlspecialchars($support_name); ?></option>
        		<?php endforeach; ?>
        	</select>
        </label> (easy) or tell your friends with a <input type="button" class="button button-tweet" value="tweet" /> (easiest).
	</p>

    <p>If you want to place the link manually here is the code:</p>
    <p><textarea cols="100" rows="3">Performance Optimization &lt;a href=&quot;http://www.w3-edge.com/wordpress-plugins/&quot; rel=&quot;external&quot;&gt;WordPress Plugins&lt;/a&gt; by W3 EDGE</textarea></p> 

	<h3>Miscellaneous Settings</h3>

	<p>	
		<input type="hidden" name="common.widget.latest" value="0" />
		<label><input type="checkbox" name="common.widget.latest" value="1"<?php checked($this->_config->get_boolean('common.widget.latest'), true); ?> /> Enable dashboard widget</label><br />
	</p>
    
    <p class="submit">
    	<input type="submit" name="Submit" class="button-primary" value="Save changes" />
    </p>
</form>

<?php include W3TC_DIR . '/inc/options/common/footer.phtml'; ?>